export const copy = {
  brand: "HTS Checkout",
  brandLine: "Payments on Hedera",
  networkTest: "Hedera testnet",
  networkLocal: "Local demo",
  demoNotice: "Testnet only. Use test HBAR and test SAUCE.",
  localNotice:
    "This is a local demo using mock contracts. The HBAR amounts shown are hypothetical.",
  heroEyebrow: "YOUR TOKEN. THEIR HBAR.",
  heroTitle: "Get paid in SAUCE.",
  heroBody:
    "Send an invoice. Your customer pays in HBAR, and the swap is settled in one transaction.",
  receive: "Create invoice",
  pay: "Pay an invoice",
  receipt: "Receipt",
  setup: "Setup",
  connectDemo: "Connect demo account",
  localRpcRequired:
    "The demo account is only usable with a localhost or 127.0.0.1 RPC URL.",
  localQuoteBody:
    "The local fixture is a fixed mock price. The amounts shown below are simulated.",
  connect: "Connect wallet",
  connecting: "Connecting…",
  noWallet:
    "No wallet detected. Open this page in your wallet's browser or use an EVM compatible wallet extension.",
  connectHint: "Attach an EVM wallet to create or pay an invoice.",
  connectFirst: "Connect your wallet to continue.",
  wrongNetwork: "Change the wallet to the set test network to proceed.",
  switchNetwork: "Switch network",
  ready: "Contract connected",
  unconfigured: "Setup required",
  unconfiguredBody:
    "Add a deployed checkout address to connect this app to the test network.",
  loadingContract: "Connecting to checkout…",
  failedContract: "Could not connect to the checkout contract.",
  createHeading: "An invoice, ready to share.",
  createBody: "Set the amount of SAUCE. Your customer pays the HBAR.",
  amount: "You receive",
  amountHint: "Up to 6 decimal places.",
  recipient: "Recipient address",
  recipientHint: "The wallet that will receive SAUCE.",
  useWallet: "Use my wallet",
  expires: "Invoice expires in",
  hour: "1 hour",
  day: "24 hours",
  week: "7 days",
  createAction: "Create invoice",
  createPending: "Creating invoice…",
  createFooter:
    "Creating an invoice sends a transaction and uses a small amount of test HBAR.",
  pathHeading: "One payment. Two tokens.",
  pathFrom: "Customer pays",
  pathTo: "Merchant receives",
  pathBody:
    "The swap and the invoice payment are done in one transaction. SaucerSwap V2 only converts the amount of HBAR required to provide the exact amount of SAUCE.",
  safetyHeading: "Built into every payment",
  safetyItems: [
    "Exact SAUCE amount for the recipient",
    "A maximum HBAR amount you approve",
    "An onchain receipt after confirmation",
  ],
  activityLabel: "Settlement",
  activityValue: "On Hedera",
  quoteLabel: "Swap route",
  quoteValue: "HBAR → SAUCE",
  payHeading: "Open your invoice.",
  payBody: "Copy and paste an invoice ID or a shared checkout link.",
  invoiceInput: "Invoice ID or checkout link",
  invoicePlaceholder: "0x… or a checkout link",
  openInvoice: "Open invoice",
  loadingInvoice: "Loading invoice…",
  invoice: "Invoice",
  requested: "Requested amount",
  merchant: "Created by",
  recipientLabel: "Recipient",
  expiresLabel: "Expires",
  active: "Awaiting payment",
  expired: "Expired",
  paid: "Paid",
  expiredBody: "This invoice is expired. Request a new one from the merchant.",
  notFound: "This invoice is not found on the configured checkout contract.",
  invalidInvoice:
    "Please provide a valid 32-byte invoice ID or a checkout link with an ID.",
  quoteHeading: "Pay with HBAR",
  quoteBody: "Get a live quote before approving your payment.",
  quoteButton: "Get HBAR quote",
  refreshQuote: "Refresh quote",
  quoting: "Getting quote…",
  estimated: "Estimated HBAR",
  maximum: "Maximum HBAR",
  slippage: "Slippage allowance",
  slippageHint:
    "If the swap needs more than this limit, the transaction reverts.",
  quoteExpires: "Quotes are valid for 30 seconds. Network fees are additional.",
  quoteStale: "This quote is no longer valid. Refresh before paying.",
  payAction: "Pay invoice",
  payPending: "Payment pending…",
  paidBody: "The recipient was paid the entire SAUCE amount.",
  paidBy: "Paid by",
  actualInput: "HBAR used",
  paymentComplete: "Payment confirmed.",
  invoiceCreated: "Invoice created.",
  refundConfirmed: "Refund withdrawal confirmed.",
  shareHeading: "Ready to send.",
  shareBody: "Send this link to your customer so they can open the invoice.",
  copyLink: "Copy link",
  copied: "Copied",
  inspectInvoice: "View invoice",
  chainExplorer: "View on HashScan",
  pendingHeading: "Waiting for confirmation",
  pendingBody:
    "Your transaction has been submitted. This page can be left open or revisited later.",
  pendingHash: "Transaction hash",
  retryReceipt: "Check confirmation",
  pendingUnavailable:
    "Confirmation could not be checked. The submitted transaction is still saved; check again before trying another payment.",
  txFailed: "The transaction reverted. No payment was made.",
  invalidAmount:
    "Please enter a positive SAUCE value (up to 6 decimal places).",
  invalidAddress: "Enter a valid EVM recipient address.",
  rejected:
    "The wallet request was rejected. No new transaction was submitted.",
  insufficient:
    "Insufficient HBAR in wallet to pay for payment and network fee.",
  noQuote: "Get a fresh HBAR quote before paying.",
  configurationMismatch: "The RPC network does not match the configured chain.",
  unsupportedChain:
    "Only Hedera testnet (296) and an explicitly configured local demo (31337) are supported.",
  contractMismatch:
    "This checkout contract has no code at the configured address.",
  invalidConfiguration:
    "The address provided for checkout or quoter is not valid.",
  refundTitle: "Refund credit",
  refundBody:
    "If a payment refund could not be returned immediately, withdraw it here.",
  refundAction: "Withdraw credit",
  refundEmpty: "No refund credit for this wallet.",
  setupHeading: "Connect your checkout.",
  setupBody:
    "Deploy the checkout contract, and then add the address of the contract to the app environment.",
  setupInstruction:
    "Place this in packages/nextjs/.env.local and restart the app:",
  setupOptional: "Optional configuration",
  setupNetwork: "Network",
  setupContract: "Checkout contract",
  setupToken: "SAUCE token",
  setupRouter: "Swap router",
  setupQuoter: "Quote contract",
  setupWrapped: "Wrapped HBAR",
  setupPoolFee: "Pool fee",
  notSet: "Not configured",
  setupWalletHint:
    "Before you can receive SAUCE, associate the token with your Hedera account.",
  associationLink: "Hedera token association guide",
  receiptEmpty: "Open an invoice to see its status and payment receipt.",
  footer: "Made for Hedera · Powered by SaucerSwap V2",
  pendingStorage:
    "Please hold this page open until confirmed. The pending transaction could not be saved by this browser.",
  copyFailed: "The link could not be copied. Select and copy the link below.",
  dismiss: "Dismiss message",
  refreshing: "Refresh status",
  walletChanged:
    "Wallet changed. Please check the linked account before proceeding.",
  unexpected: "The request could not be completed.",
} as const;
